package woven_bank;

// Start of user code for imports
// End of user code

/**
 * ConsoleLogger class definition.
 * Generated by the TouchCORE code generator.
 */
class ConsoleLogger extends Logger {
    
    protected Account subject;
    
    ConsoleLogger(Account subject) {
        this.subject = subject;
    }

    void log(String message) {
        boolean isConsoleLoggingEnabled = subject.isConsoleLoggingEnabled();
        if (isConsoleLoggingEnabled) {
            System.out.println(message);
        }
    }

    Account getSubject() {
        return this.subject;
    }

    boolean setSubject(Account newObject) {
        this.subject = newObject;
        return true;
    }
}
