package woven_bank;

import java.util.LinkedList;

// Start of user code for imports
// End of user code

/**
 * Logger class definition.
 * Generated by the TouchCORE code generator.
 */
class Logger {
    
    protected Account subject;
    
    void log(String message) {
        /* TODO: No message view defined */
    }

    Account getSubject() {
        return this.subject;
    }

    boolean setSubject(Account newObject) {
        this.subject = newObject;
        return true;
    }
}
