package woven_bank;

import java.lang.RuntimeException;

// Start of user code for imports
// End of user code

/**
 * NotEnoughFundsException class definition.
 * Generated by the TouchCORE code generator.
 */
public class NotEnoughFundsException extends RuntimeException {
    
    public NotEnoughFundsException() {
        /* TODO: No message view defined */
    }
}
