package bankwithlogging;

import javax.swing.DefaultListModel;
import javax.swing.JButton;
import java.awt.event.ActionListener;
import javax.swing.event.DocumentListener;
import javax.swing.JTextField;
import javax.swing.JList;
import javax.swing.event.DocumentEvent;
import java.awt.event.ActionEvent;

// Start of user code for imports
// End of user code

/**
 * CustomerListener class definition.
 * Generated by the TouchCORE code generator.
 */
public class CustomerListener implements ActionListener, DocumentListener {
    
    protected JButton myJButton;
    protected JTextField myJTextField;
    protected DefaultListModel<Customer> customerListModel;
    protected JButton accountButton;
    protected JList<Customer> customerList;
    
    public CustomerListener(JButton button, JTextField field, DefaultListModel<Customer> listModel, JButton accButton, JList<Customer> custList) {
        this.myJButton = button;
        this.myJTextField = field;
        this.customerListModel = listModel;
        this.accountButton = accButton;
        this.customerList = custList;
    }

    JButton getMyJButton() {
        /* TODO: No message view defined */
        return null;
    }

    boolean setMyJButton(JButton newObject) {
        /* TODO: No message view defined */
        return false;
    }

    JTextField getMyJTextField() {
        /* TODO: No message view defined */
        return null;
    }

    boolean setMyJTextField(JTextField newObject) {
        /* TODO: No message view defined */
        return false;
    }

    public void actionPerformed(ActionEvent e) {
        String name = myJTextField.getText();
        Customer customer = new Customer(name);
        customerListModel.insertElementAt(customer, 0);
        myJTextField.requestFocusInWindow();
        myJTextField.setText("");
        accountButton.setEnabled(true);
        customerList.setSelectedIndex(0);
    }

    DefaultListModel<Customer> getCustomerListModel() {
        /* TODO: No message view defined */
        return null;
    }

    boolean setCustomerListModel(DefaultListModel<Customer> newObject) {
        /* TODO: No message view defined */
        return false;
    }

    public void insertUpdate(DocumentEvent e) {
        myJButton.setEnabled(true);
    }

    public void removeUpdate(DocumentEvent e) {
        String text = myJTextField.getText();
        if (text.length() == 0) {
            myJButton.setEnabled(false);
        }
    }

    public void changedUpdate(DocumentEvent e) {
        String text = myJTextField.getText();
        if (text.length() == 0) {
            myJButton.setEnabled(false);
        } else {
            myJButton.setEnabled(true);
        }
    }

    JButton getAccountButton() {
        /* TODO: No message view defined */
        return null;
    }

    boolean setAccountButton(JButton newObject) {
        /* TODO: No message view defined */
        return false;
    }

    JList<Customer> getCustomerList() {
        /* TODO: No message view defined */
        return null;
    }

    boolean setCustomerList(JList<Customer> newObject) {
        /* TODO: No message view defined */
        return false;
    }
}
